# Generated by Django 6.0 on 2026-01-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={},
        ),
    ]
