# Generated by Django 6.0 on 2026-01-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_propertyunlock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='updatedAt',
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
