# Generated by Django 6.0 on 2026-02-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestquote',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
