# Generated by Django 6.0 on 2026-01-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_users_full_name_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('buyer', 'Buyer'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
