# Generated by Django 6.0 on 2026-01-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
