# Generated by Django 6.0 on 2026-01-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('buyer', 'Buyer'), ('admin', 'Admin')], default='buyer', max_length=20),
        ),
    ]
