# Generated by Django 6.0 on 2026-02-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
    ]
