# Generated by Django 6.0 on 2026-01-21 05:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('propertyName', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('propertyAddress', models.CharField(max_length=255)),
                ('propertyType', models.CharField(max_length=255)),
                ('propertyBedrooms', models.CharField(blank=True, max_length=255, null=True)),
                ('propertyBathrooms', models.CharField(blank=True, max_length=255, null=True)),
                ('propertyParking', models.CharField(blank=True, max_length=255, null=True)),
                ('propertyBuildYear', models.CharField(blank=True, max_length=255, null=True)),
                ('propertyHasPool', models.BooleanField(default=False)),
                ('propertyIsStrataProperty', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('propertyFeatureImage', models.ImageField(blank=True, null=True, upload_to='property_feature_images/')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('feature', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='property.property')),
            ],
            options={
                'verbose_name': 'Property Feature',
                'verbose_name_plural': 'Property Features',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInspectionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='property_inspection_reports/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to='property.property')),
            ],
            options={
                'verbose_name': 'Property Inspection Report',
                'verbose_name_plural': 'Property Inspection Reports',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOptionalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='property_optional_reports/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_reports', to='property.property')),
            ],
            options={
                'verbose_name': 'Property Optional Report',
                'verbose_name_plural': 'Property Optional Reports',
                'ordering': ['-createdAt'],
            },
        ),
    ]
