# Generated by Django 6.0 on 2026-01-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='propertyBuiltIn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyFeatureImage',
            field=models.ImageField(default=1, upload_to='property_feature_images/'),
            preserve_default=False,
        ),
    ]
