# Generated by Django 6.0 on 2026-01-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_propertybuiltin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='propertyBuiltIn',
        ),
    ]
