# Generated by Django 6.0 on 2026-01-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_property_propertybuiltin'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
