# Generated by Django 6.0 on 2026-01-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(default=1, upload_to='property_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyinspectionreport',
            name='report',
            field=models.FileField(default=1, upload_to='property_inspection_reports/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyoptionalreport',
            name='report',
            field=models.FileField(default=1, upload_to='property_optional_reports/'),
            preserve_default=False,
        ),
    ]
