# Generated by Django 6.0 on 2026-02-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_inspection_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='property',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='Inspection',
        ),
    ]
