# Generated by Django 6.0 on 2026-02-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_inspection_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='propertyPortfolio',
            field=models.FileField(blank=True, null=True, upload_to='property_portfolio/'),
        ),
    ]
