# Generated by Django 6.0 on 2026-02-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_propertyportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='propertyBio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
