# Generated by Django 6.0 on 2026-02-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_property_propertybio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='propertyBio',
            new_name='propertyDetails',
        ),
    ]
