# Generated by Django 6.0 on 2026-02-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_rename_propertybio_property_propertydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propertyDetails',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
