# Generated by Django 6.0 on 2026-03-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_property_propertydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='propertyPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='propertyinspectionreport',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertyoptionalreport',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
